import axios from 'axios'
import Head from 'next/head'
import Image from 'next/image'
import Button from '../components/Button'

export default function Home(props) {
  return (
    <div className='bg-black'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <div className='bg-blue-500 flex justify-between items-end  md:p-7 text-white'>
    <h1>logo</h1>
    <div className='flex gap-2'>
      <Button path={'/'} text='home' />
      <Button path={'/about'} text='about' />
    </div>
    </div>
    </div>
  )
}

// export async function getStaticProps(){
//   const res = await axios.get('http://localhost:3000/api/blog')
//   const blog = res.data
//   console.log(blog)
//   return{
//     props:{
//       blog
//     }
//   }
// }